version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:13.3
    command:
      - "postgres"
    environment:
      POSTGRES_DB: "checklens"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_pass"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ../../migrations/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - pg_net

networks:
  pg_net:
    driver: bridge